# syntax=docker/dockerfile:1
FROM busybox
ADD ./LICENSE  /knowledgeBase/LICENSE
ADD ./CITATION.cff  /knowledgeBase/CITATION.cff
ADD ./Cps2_Network.pickle  /knowledgeBase/currentSolution.pickle
ADD ./Cps2_Network.xml  /knowledgeBase/currentSolution.xml