# syntax=docker/dockerfile:1
FROM busybox
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/train/banana-ok /learningBase/train/banana-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/train/banana-def /learningBase/train/banana-def
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/validation/banana-ok /learningBase/validation/banana-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/validation/banana-def /learningBase/validation/banana-def