# syntax=docker/dockerfile:1
FROM busybox
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/apple-ok /learningBase/train/apple-ok
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/apple-def /learningBase/train/apple-def
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/apple-ok /learningBase/validation/apple-ok
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/apple-def /learningBase/validation/apple-def
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/banana-ok /learningBase/train/banana-ok
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/banana-def /learningBase/train/banana-def
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/banana-ok /learningBase/validation/banana-ok
COPY ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/banana-def /learningBase/validation/banana-def