# syntax=docker/dockerfile:1
FROM busybox
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/train /learningBase/train
Add ./../../data/pump-impeller-dataset/train /learningBase/train
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation /learningBase/validation
Add ./../../data/pump-impeller-dataset/validation /learningBase/validation