# syntax=docker/dockerfile:1
FROM busybox
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/train/orange-ok /learningBase/train/orange-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/train/orange-def /learningBase/train/orange-def
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/validation/orange-ok /learningBase/validation/orange-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset-blurredWithSigma6/validation/orange-def /learningBase/validation/orange-def