# syntax=docker/dockerfile:1
FROM busybox
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/apple-ok /learningBase/train/apple-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/apple-def /learningBase/train/apple-def
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/apple-ok /learningBase/validation/apple-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/apple-def /learningBase/validation/apple-def