# syntax=docker/dockerfile:1
FROM tensorflow/tensorflow
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install matplotlib
Run pip3 install SciPy
Add ./../../code/annRequests_TensorFlow /codeBase/