# syntax=docker/dockerfile:1
FROM busybox
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/train/banana-ok /learningBase/train/banana-ok
Add ./../../data/fruits-fresh-and-rotten-fruits-dataset/validation/banana-ok /learningBase/validation/banana-ok